- Scenes/main.tscn
- Scripts/chickadee.gd
- Scripts/game_manager.gd
change score update to UI manager-script. later UI updates can finish in one script.
> UI manager

- Scenes/EnemyScenes/chickadee.tscn
- Scenes/EnemyScenes/healthBar.gd
- Scenes/enemy_manager.tscn
- Scripts/chickadee.gd
- Scripts/enemy_manager.gd
Added a health bar to the enemy, as well as a small gap of time before the next enemy spawns in.
> Health Bar

- Scenes/expBar.tscn
- Scenes/main.tscn
- Scripts/Player.gd
- Scripts/chickadee.gd
- Scripts/expBar.gd
Added an exp bar and levelling up system
> Exp Bar/Levelling Up

- Scenes/anim_claymore_meter.gd
- Scenes/anim_claymore_meter.tscn
- Scripts/chickadee.gd
Added the first functionality to the "claymore" weapon type, where the player will hold down the button to charge their attack. I created the measuring process, complete with a meter that tracks how charged your swing is.
> Claymore Weapon Setup

- Scenes/anim_claymore_meter.tscn
- Scripts/chickadee.gd
Added claymore dealing damage upon releasing the button
> Claymore Damage

- Scenes/main.tscn
- Scripts/Player.gd
- Scripts/add_strength_button.gd
- Scripts/chickadee.gd
> UI Additions

- Scenes/anim_claymore_meter.tscn
- Scenes/plaDA20.tmp
- Scripts/Player.gd
- Scripts/chickadee.gd
Handles inputs in player script instead of enemy script now
> Project Reformatting

- Scenes/main.tscn
- Scripts/Player.gd
- Scripts/add_strength_button.gd
buttons can be equipped in the menu, and it will display as such. (Only on "Sword 1" at the moment)
> Equipping UI

- Scenes/main.tscn
- Scripts/EquipmentManager.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
player can now properly equip weapons
> Equip Weapons

- Scenes/main.tscn
- Scripts/EquipmentManager.gd
- Scripts/Player.gd
Claymores can be used on either hand
Must be purchased first
> Weapon Purchase Setup

- Scripts/EquipmentManager.gd
- Scripts/Player.gd
(weapons can be equipped, except drills)
> Weapons Equippable

- Scenes/main.tscn
- Scenes/scoreboard.tscn
- Scripts/EquipmentManager.gd
- Scripts/Player.gd
Added functionality to crit damage and energy regen buttons.
> Added Crit Damage/Energy Regen

- Scenes/ultMeterScript.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
implemented the middle button ult functionality
> implemented ult

- Scripts/EquipmentManager.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
Drill functionality is essentially finalized
> Drill Bug Fixes

- Scenes/PlayerStats.gd
- Scenes/PlayerStats.tscn
- Scenes/main.tscn
- Scenes/party_member_stat_holder_ui.gd
- Scripts/PartyMember.gd
- Scripts/RecruitPartyMember.gd
> Player UI fix

- Scenes/PlayerStats.gd
- Scenes/main.tscn
- Scenes/party_member_stat_holder_ui.gd
- Scenes/scoreboard.tscn
- Scripts/PartyMember.gd
Adds a color tint to upgraded text
Removed some UI elements, much less cluttered.
> UI Fixes/Upgrades

- Scenes/PartyMember.tscn
- Scenes/PlayerStats.gd
- Scenes/party_member_stat_holder_ui.gd
- Scripts/PartyMember.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
LineText gets Name, exp tweak, upgrade points cost money
> Various UI Fixes/Tweaks

- Scenes/EnemyScenes/mushroom.tscn
- Scripts/enemy_manager.gd
added mushroom enemy to enemy pool
> mushroom enemy

- Scenes/current_monster_icon_button.tscn
- Scripts/CaptureList.gd
- Scripts/PlayerMonsterList.gd
- Scripts/chickadee.gd
applied the functionality of selecting and applying passives
> Passives Functionality

- Scenes/MainShopUI.gd
- Scenes/shop_ui.tscn
UI now has animations to traverse different menus
> UI Animations

- Scenes/MainShopUI.gd
- Scenes/shop_ui.tscn
> UI Sliders

- Scenes/EnemyScenes/Health_Bar.gd
- Scenes/PlayerStats.gd
- Scripts/PartyMember.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
Added break damage reduction, break damage multiplier, and unlocking break enemies at a certain level
> break modifications

- Scripts/chickadee.gd
- Scripts/qte.gd
- break_effect.gd
- break_effect.tscn
> break effect scaling

- Scripts/chickadee.gd
- Scripts/qte.gd
Can no longer click on enemies while under break animation
> Bug Fix (Hi Yifei)

- Scenes/PartyMember.tscn
- Scenes/main.tscn
- Scenes/qte.tscn
- Scripts/Player.gd
- Scripts/chickadee.gd
- Scripts/qte.gd
Fixed display bugs and added a track damage function, tracks when a particularly heavy hit is complete
> Bug Fixes and Polish

- Scenes/EnemyScenes/chickadee.tscn
- Scenes/break_effect.tscn
- Scripts/chickadee.gd
enemy flashes red upon being broken
> Enemy Flash

- Scenes/ExperienceParticle.tscn
- Scenes/expBar.tscn
- Scenes/main.tscn
- Scripts/ExperienceParticle.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
- Scripts/expBar.gd
Gaining exp is now a bit more fun! Exp particles spawn upon defeating an enemy that shoot to your exp bar and fill it up
> Exp Gain Polish

- Scenes/EnemyScenes/chickadee.tscn
- Scenes/EnemyScenes/chicken.tscn
- Scenes/EnemyScenes/ghost.tscn
- Scenes/EnemyScenes/mushroom.tscn
- Scenes/EnemyScenes/slime.tscn
- Scenes/scoreboard.tscn
- Scripts/ExperienceParticle.gd
- Scripts/Player.gd
- Scripts/chickadee.gd
Enemy scale increases in a fluid, jiggly manner upon mouse hover
Score jiggles upon update, creating a frantic and energetic sense of progress
Exp Particles float a bit before being whisked to the EXP bar
> GameFeel Polish

- Scenes/EnemyScenes/chickadee.tscn
- Scenes/EnemyScenes/chicken.tscn
- Scenes/EnemyScenes/ghost.tscn
- Scenes/EnemyScenes/mushroom.tscn
- Scenes/EnemyScenes/slime.tscn
- Scripts/Player.gd
- Scripts/Weapon.gd
- Scripts/chickadee.gd
All status effects and its base functionality implemented
> Status Effect Implementation

- Scenes/ultMeter.tscn
- Scripts/chickadee.gd
- Scripts/qte.gd
> qte set positions
